In [1]:
import numpy as np
import tensorflow as tf

In [2]:
n_steps = 2
n_inputs = 3
n_neurons = 5

In [3]:
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])

basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

W0628 14:17:10.703769 139772190861120 deprecation.py:323] From <ipython-input-3-6853c7d6d297>:3: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
W0628 14:17:10.705010 139772190861120 deprecation.py:323] From <ipython-input-3-6853c7d6d297>:4: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0628 14:17:10.747756 139772190861120 deprecation.py:506] From /home/sean/pyenv/py37/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtyp

In [4]:
init = tf.global_variables_initializer()

In [5]:
X_batch = np.array([
        [[0, 1, 2], [9, 8, 7]], # instance 1
        [[3, 4, 5], [0, 0, 0]], # instance 2
        [[6, 7, 8], [6, 5, 4]], # instance 3
        [[9, 0, 1], [3, 2, 1]], # instance 4
    ])

with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [6]:
print(outputs_val)

[[[ 0.88489777  0.5079479  -0.4899479   0.13642117 -0.11085574]
  [ 0.99999994  0.96607435 -0.99997187  0.99990547  0.9998436 ]]

 [[ 0.9999221   0.8559238  -0.989063    0.9286411   0.8585555 ]
  [-0.5311038   0.6279739   0.50437367  0.67775273  0.15696456]]

 [[ 0.9999998   0.9637322  -0.99982333  0.99640346  0.99077106]
  [ 0.99995834  0.9242043  -0.9953824   0.9989591   0.9952701 ]]

 [[ 0.99826163  0.87961054 -0.99997044  0.99062455  0.9977645 ]
  [ 0.93960446  0.7245399  -0.7367247   0.9762548   0.9243605 ]]]
