In [1]:
import numpy as np
import tensorflow as tf

In [2]:
n_steps = 2
n_inputs = 3
n_neurons = 5

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
X_seqs = tf.unstack(tf.transpose(X, perm=[1, 0, 2]))

basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.nn.static_rnn(basic_cell, X_seqs, dtype=tf.float32)

outputs = tf.transpose(tf.stack(output_seqs), perm=[1, 0, 2])

W0628 14:11:21.345861 140084325431104 deprecation.py:323] From <ipython-input-2-29283a5349bd>:8: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
W0628 14:11:21.346878 140084325431104 deprecation.py:323] From <ipython-input-2-29283a5349bd>:9: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
W0628 14:11:21.355773 140084325431104 deprecation.py:506] From /home/sean/pyenv/py37/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance w

In [3]:
init = tf.global_variables_initializer()

In [4]:
X_batch = np.array([
        # t = 0      t = 1 
        [[0, 1, 2], [9, 8, 7]], # instance 1
        [[3, 4, 5], [0, 0, 0]], # instance 2
        [[6, 7, 8], [6, 5, 4]], # instance 3
        [[9, 0, 1], [3, 2, 1]], # instance 4
    ])

with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [5]:
print(outputs_val)

[[[ 0.54403156  0.56879187 -0.34342363  0.25884685  0.7665351 ]
  [-0.8776654   0.999999   -0.99868363  0.9999221   0.998564  ]]

 [[ 0.23339108  0.9955118  -0.9275944   0.96940005  0.9857969 ]
  [ 0.8443355   0.8146332  -0.7055521  -0.02453475 -0.08422599]]

 [[-0.13351636  0.99996316 -0.99424267  0.9991802   0.99922603]
  [ 0.07663784  0.9999499  -0.99729973  0.99804246  0.93929106]]

 [[-0.6933267   0.8593639  -0.9999348   0.86383724 -0.99088097]
  [ 0.5338715   0.89973015 -0.9845031   0.97315717 -0.35741174]]]
